# Nifty 500 stocks — rotated daily for investment reel
# Format: (display_name, yfinance_ticker)
# Script picks one per day based on day-of-year index

NIFTY500 = [
    ("Reliance Industries", "RELIANCE.NS"),
    ("TCS", "TCS.NS"),
    ("HDFC Bank", "HDFCBANK.NS"),
    ("Infosys", "INFY.NS"),
    ("ICICI Bank", "ICICIBANK.NS"),
    ("Hindustan Unilever", "HINDUNILVR.NS"),
    ("ITC", "ITC.NS"),
    ("SBI", "SBIN.NS"),
    ("Bharti Airtel", "BHARTIARTL.NS"),
    ("Kotak Mahindra Bank", "KOTAKBANK.NS"),
    ("L&T", "LT.NS"),
    ("Axis Bank", "AXISBANK.NS"),
    ("Asian Paints", "ASIANPAINT.NS"),
    ("Maruti Suzuki", "MARUTI.NS"),
    ("Titan Company", "TITAN.NS"),
    ("Bajaj Finance", "BAJFINANCE.NS"),
    ("Wipro", "WIPRO.NS"),
    ("HCL Technologies", "HCLTECH.NS"),
    ("UltraTech Cement", "ULTRACEMCO.NS"),
    ("Nestle India", "NESTLEIND.NS"),
    ("Adani Enterprises", "ADANIENT.NS"),
    ("Tata Steel", "TATASTEEL.NS"),
    ("Sun Pharma", "SUNPHARMA.NS"),
    ("ONGC", "ONGC.NS"),
    ("NTPC", "NTPC.NS"),
    ("Power Grid", "POWERGRID.NS"),
    ("Coal India", "COALINDIA.NS"),
    ("JSW Steel", "JSWSTEEL.NS"),
    ("Bajaj Finserv", "BAJAJFINSV.NS"),
    ("Tata Consultancy", "TCS.NS"),
    ("Mahindra & Mahindra", "M&M.NS"),
    ("Dr Reddy's", "DRREDDY.NS"),
    ("Cipla", "CIPLA.NS"),
    ("Divis Laboratories", "DIVISLAB.NS"),
    ("Eicher Motors", "EICHERMOT.NS"),
    ("Hero MotoCorp", "HEROMOTOCO.NS"),
    ("Hindalco", "HINDALCO.NS"),
    ("IndusInd Bank", "INDUSINDBK.NS"),
    ("Tata Consumer", "TATACONSUM.NS"),
    ("Britannia", "BRITANNIA.NS"),
    ("Grasim Industries", "GRASIM.NS"),
    ("Tech Mahindra", "TECHM.NS"),
    ("Shree Cement", "SHREECEM.NS"),
    ("Pidilite Industries", "PIDILITIND.NS"),
    ("Havells India", "HAVELLS.NS"),
    ("Godrej Consumer", "GODREJCP.NS"),
    ("Dabur India", "DABUR.NS"),
    ("Marico", "MARICO.NS"),
    ("Berger Paints", "BERGEPAINT.NS"),
    ("Torrent Pharma", "TORNTPHARM.NS"),
    ("Muthoot Finance", "MUTHOOTFIN.NS"),
    ("Cholamandalam", "CHOLAFIN.NS"),
    ("SBI Life Insurance", "SBILIFE.NS"),
    ("HDFC Life", "HDFCLIFE.NS"),
    ("ICICI Prudential", "ICICIPRULI.NS"),
    ("Bajaj Auto", "BAJAJ-AUTO.NS"),
    ("TVS Motor", "TVSMOTOR.NS"),
    ("Exide Industries", "EXIDEIND.NS"),
    ("Amara Raja", "AMARAJABAT.NS"),
    ("Voltas", "VOLTAS.NS"),
    ("Blue Star", "BLUESTARCO.NS"),
    ("Crompton Greaves", "CROMPTON.NS"),
    ("Polycab India", "POLYCAB.NS"),
    ("KEI Industries", "KEI.NS"),
    ("ABB India", "ABB.NS"),
    ("Siemens India", "SIEMENS.NS"),
    ("Cummins India", "CUMMINSIND.NS"),
    ("Thermax", "THERMAX.NS"),
    ("Bharat Electronics", "BEL.NS"),
    ("HAL", "HAL.NS"),
    ("BEL", "BEL.NS"),
    ("IRCTC", "IRCTC.NS"),
    ("Indian Railway Finance", "IRFC.NS"),
    ("Zomato", "ZOMATO.NS"),
    ("Nykaa", "NYKAA.NS"),
    ("Paytm", "PAYTM.NS"),
    ("DMart", "DMART.NS"),
    ("Trent", "TRENT.NS"),
    ("Vedanta", "VEDL.NS"),
    ("Suzlon Energy", "SUZLON.NS"),
    ("Adani Ports", "ADANIPORTS.NS"),
    ("Adani Power", "ADANIPOWER.NS"),
    ("Adani Green", "ADANIGREEN.NS"),
    ("Adani Total Gas", "ATGL.NS"),
    ("Tata Power", "TATAPOWER.NS"),
    ("JSW Energy", "JSWENERGY.NS"),
    ("Torrent Power", "TORNTPOWER.NS"),
    ("CESC", "CESC.NS"),
    ("PFC", "PFC.NS"),
    ("REC Limited", "RECLTD.NS"),
    ("IREDA", "IREDA.NS"),
    ("Bank of Baroda", "BANKBARODA.NS"),
    ("PNB", "PNB.NS"),
    ("Canara Bank", "CANBK.NS"),
    ("Union Bank", "UNIONBANK.NS"),
    ("Indian Bank", "INDIANB.NS"),
    ("Federal Bank", "FEDERALBNK.NS"),
    ("IDFC First Bank", "IDFCFIRSTB.NS"),
    ("AU Small Finance", "AUBANK.NS"),
    ("Bandhan Bank", "BANDHANBNK.NS"),
    ("City Union Bank", "CUB.NS"),
    ("Karur Vysya Bank", "KARURVYSYA.NS"),
]


def get_todays_stock():
    """Returns today's stock based on day-of-year rotation."""
    from datetime import datetime
    day_of_year = datetime.now().timetuple().tm_yday
    idx = day_of_year % len(NIFTY500)
    return NIFTY500[idx]
